apiVersion: container.gcp.crossplane.io/v1beta1
kind: GKECluster
metadata:
  name: ${{values.clusterRef}}
  labels:
    backstage.io/kubernetes-id: ${{values.component_id}}
spec:
  forProvider:
    addonsConfig:
      cloudRunConfig:
        disabled: true
      dnsCacheConfig:
        enabled: false
      gcePersistentDiskCsiDriverConfig:
        enabled: true
      horizontalPodAutoscaling:
        disabled: true
      httpLoadBalancing:
        disabled: true
      istioConfig:
        disabled: true
        auth: "AUTH_NONE"
      kalmConfig:
        enabled: true
      kubernetesDashboard:
        disabled: true
      networkPolicyConfig:
        disabled: false
    location: northamerica-northeast1-a
    binaryAuthorization:
      enabled: false
    ipAllocationPolicy:
      useIpAliases: true
      createSubnetwork: true
    legacyAbac:
      enabled: false
    loggingService: "logging.googleapis.com/kubernetes"
    masterAuth:
      clientCertificateConfig:
        issueClientCertificate: false
    monitoringService: "monitoring.googleapis.com/kubernetes"
    network: "${{values.networkRef}}"
    networkPolicy:
      enabled: true
      provider: CALICO
    podSecurityPolicyConfig:
      enabled: true
  providerConfigRef:
    name: gcp-stack-template-provider-${{values.gcpProject}}-${{values.destination.repo}}
---
apiVersion: container.gcp.crossplane.io/v1alpha1
kind: NodePool
metadata:
  name: ${{values.clusterRef}}-np
  labels:
    backstage.io/kubernetes-id: ${{values.component_id}}
spec:
  forProvider:
    autoscaling:
      autoprovisioned: false
      enabled: true
      maxNodeCount: ${{values.clusterNodesCount}}
      minNodeCount: ${{values.clusterNodesCount}}
    clusterRef:
      name: ${{values.clusterRef}}
    config:
      sandboxConfig:
        sandboxType: gvisor
      diskSizeGb: 120
      diskType: pd-ssd
      imageType: cos_containerd
      labels:
        test-label: crossplane-created
      machineType: n1-standard-2
      oauthScopes:
        - "https://www.googleapis.com/auth/devstorage.read_only"
        - "https://www.googleapis.com/auth/logging.write"
        - "https://www.googleapis.com/auth/monitoring"
        - "https://www.googleapis.com/auth/servicecontrol"
        - "https://www.googleapis.com/auth/service.management.readonly"
        - "https://www.googleapis.com/auth/trace.append"
    initialNodeCount: ${{values.clusterNodesCount}}
    locations:
      - "northamerica-northeast1-a"
  providerConfigRef:
    name: gcp-stack-template-provider-${{values.gcpProject}}-${{values.destination.repo}}
