apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id | dump}}
  description: ${{values.description | dump}}
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
    argocd/app-name: ${{values.destination.repo | dump}}
    backstage.io/kubernetes-id: ${{values.component_id | dump}}
spec:
  type: service
  lifecycle: experimental
  owner: ${{values.destination.owner | dump}}
